[build]
  command = "CI=false npm run build"
  publish = "build/"

[[redirects]]
  from = "/api/csv"
  to = "https://drive.google.com/uc?export=download&id=19191SkOve-WWZsWK8SvWPPgdMrJsIoT9"
  status = 200
  force = true
